# Generated by Django 4.1.3 on 2022-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='discription',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
