# Generated by Django 4.1.3 on 2022-12-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_post_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
