# Generated by Django 4.1.3 on 2022-12-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
